name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

stages:
  - deploy

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    stage: deploy
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Remix
        run: npm run build

      - name: Start Remix Dev Server
        run: npm run dev
        if: github.ref == github.repository.default_branch
